"""Common constants for the package."""

CATALOG_SECTORS = 2
CATALOG_SECTOR1 = 0
CATALOG_SECTOR2 = 1
SECTORS = 10
SECTOR_SIZE = 256
TRACK_SIZE = SECTORS * SECTOR_SIZE
DOUBLE_TRACKS = 80
SINGLE_TRACKS = 40
DOUBLE_SECTORS = DOUBLE_TRACKS * SECTORS
SINGLE_SECTORS = SINGLE_TRACKS * SECTORS
MAX_FILES = 31

MMB_MAX_ENTRIES = 511
MMB_INDEX_ENTRY_SIZE = 16
MMB_INDEX_SIZE = (MMB_MAX_ENTRIES + 1) * MMB_INDEX_ENTRY_SIZE
MMB_DISK_SIZE = TRACK_SIZE * DOUBLE_TRACKS
MMB_SIZE = MMB_INDEX_SIZE + MMB_MAX_ENTRIES * MMB_DISK_SIZE

MMB_STATUS_OFFSET = 15

MMB_STATUS_LOCKED = 0
MMB_STATUS_UNLOCKED = 15
MMB_STATUS_UNINITIALIZED = 240

MMB_STATUS_UNINITIALIZED_MASK = 240
